apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress-fairmece
  namespace: default
spec:
  ingressClassName: traefik # Specify your Ingress Controller class
  rules:
  - host: "jenkins.fairmerce.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-operator-http-example # The name of your Jenkins Service
            port:
              number: 8080 # The port the Jenkins Service exposes