apiVersion: v2
name: karpenter-root
description: Karpenter parent chart
type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: karpenter
    version: "1.8.6"
    repository: "oci://public.ecr.aws/karpenter"